
fatal: unable to access 'https://github.com/computergeek1100/ri-covid-graphs.git/': gnutls_handshake() failed: Error in the pull function.
fatal: unable to access 'https://github.com/computergeek1100/ri-covid-graphs.git/': gnutls_handshake() failed: Error in the pull function.
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.2     ✔ purrr   0.3.4
✔ tibble  3.0.4     ✔ dplyr   1.0.2
✔ tidyr   1.1.2     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Attaching package: ‘plotly’

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout


Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [sheets.googleapis.com] Operation timed out after 10001 milliseconds with 0 out of 0 bytes received
Calls: read_sheet ... request_fetch -> request_fetch.write_memory -> <Anonymous>
Execution halted
